# Generated by Django 4.0.4 on 2022-10-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_inicial', models.IntegerField(blank=True, default='DEFAULT VALUE', null=True)),
                ('produto', models.CharField(max_length=100)),
                ('NCM', models.IntegerField(default=None)),
                ('marca_produto', models.CharField(max_length=200)),
                ('codigo_produto', models.IntegerField(default=None)),
                ('valor_custo', models.IntegerField()),
                ('valor_venda', models.IntegerField()),
                ('qtde_estoque', models.IntegerField()),
            ],
            options={
                'db_table': 'store_estoque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cnpj_cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('CEP', models.IntegerField(default=None)),
                ('logradouro', models.CharField(default=None, max_length=100)),
                ('numero', models.CharField(default=None, max_length=100)),
                ('complemento', models.CharField(default=None, max_length=100)),
                ('bairro', models.CharField(default=None, max_length=100)),
                ('ESTADO', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espirito Santo'), ('GO', 'Goias'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piaui'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', ' Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default=None, max_length=20)),
                ('cidade', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=500)),
                ('codigo_produto', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('desconto', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('valor_total', models.DecimalField(decimal_places=1000, max_digits=1000)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cnpj_cpf_cliente', models.IntegerField()),
                ('forma_de_pagamento', models.CharField(choices=[('CRÉDITO', 'Crédito'), ('DEBITO', 'Débito'), ('PIX', 'pix'), ('DINHEIRO', 'Dinheiro')], max_length=20)),
                ('fechar_venda', models.CharField(choices=[('NOTA DE PEDIDO', 'Nota de pedido'), ('NOTA FISCAL', 'Nota fiscal')], max_length=20)),
                ('fechar_caixa', models.IntegerField()),
                ('valor_total_vendas', models.CharField(choices=[('DIARIO', 'Diário'), ('SEMANAL', 'Semanal'), ('QUINZENAL', 'Quinzenal'), ('MENSAL', 'Mensal')], max_length=20)),
            ],
        ),
    ]
